### ISSUE TITLE
Change style of tables

### ISSUE THREAD

**Issue by RePierre** [eemlcommunity/ro_benchmark_leaderboard#24]

**Comment by dumitrescustefan** [comment]
1. tabels should have on the first column "Rank" as header and numbers from 1 to n
2. let's keep the tables white with light gray lines separating rows, that's the theme of the site
3. a little less spacing between rows and inside cells, and font should be smaller than the standard of the page
4. bold the dataset name and the model name

**Comment by RePierre** [comment]
Since item 1. is related to development not styling, I've created issue #30 for it.
